"""Initial migration

Revision ID: 5a0a73b27471
Revises: 
Create Date: 2026-01-03 02:01:37.384309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0a73b27471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='adminstatus'), nullable=True, comment='状态'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('admin_username', sa.String(length=50), nullable=False, comment='操作用户名'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='操作对象类型'),
    sa.Column('target_id', sa.String(length=50), nullable=False, comment='操作对象ID'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='操作详情'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='操作时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('license_key', sa.String(length=50), nullable=False, comment='授权码'),
    sa.Column('product_code', sa.String(length=50), nullable=False, comment='关联产品标识'),
    sa.Column('max_devices', sa.Integer(), nullable=True, comment='最大设备数限制'),
    sa.Column('expire_at', sa.Date(), nullable=False, comment='过期时间'),
    sa.Column('status', sa.Enum('UNACTIVATED', 'ACTIVATED', 'EXPIRED', 'REVOKED', name='licensestatus'), nullable=True, comment='状态'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_index(op.f('ix_licenses_product_code'), 'licenses', ['product_code'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('product_code', sa.String(length=50), nullable=False, comment='产品唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('public_key', sa.String(length=1000), nullable=False, comment='RSA公钥'),
    sa.Column('private_key', sa.String(length=2000), nullable=False, comment='RSA私钥'),
    sa.Column('heartbeat_interval', sa.Integer(), nullable=True, comment='心跳间隔（秒）'),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='productstatus'), nullable=True, comment='产品状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('license_id', sa.Integer(), nullable=False, comment='关联授权ID'),
    sa.Column('product_code', sa.String(length=50), nullable=False, comment='产品标识'),
    sa.Column('client_fp', sa.String(length=100), nullable=False, comment='客户端指纹'),
    sa.Column('client_type', sa.Enum('GUI', 'CLI', 'SERVICE', 'PLUGIN', name='clienttype'), nullable=False, comment='客户端类型'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='客户端IP地址'),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True, comment='最后心跳时间'),
    sa.Column('status', sa.Enum('NORMAL', 'ABNORMAL', 'DISABLED', name='clientstatus'), nullable=True, comment='状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id', 'client_fp', name='uq_license_client_fp')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_license_id'), 'clients', ['license_id'], unique=False)
    op.create_index(op.f('ix_clients_product_code'), 'clients', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_product_code'), table_name='clients')
    op.drop_index(op.f('ix_clients_license_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_licenses_product_code'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###